CREATE DATABASE abel;
USE abel;

CREATE TABLE `ADMIN`(
    ADMIN_ID 	VARCHAR(20) PRIMARY KEY,
	PASSWD 		VARCHAR(100),
	JOIN_DT 	DATETIME
);

INSERT INTO `ADMIN` VALUES ('admin' , 'P@ssw0rd' , NOW());

CREATE TABLE MEMBER (
	MEMBER_ID		VARCHAR(20) PRIMARY KEY,
    MEMBER_PASSWD	VARCHAR(1000),
    MEMBER_NM		VARCHAR(50),
    EMAIL			VARCHAR(20),
    EMAILSTS_YN 	VARCHAR(20),
	DATE_BIRTH 		VARCHAR(20),
    SEX 			VARCHAR(10),
	HP 				VARCHAR(20),
	SMSSTS_YN 		VARCHAR(20),
	ZIPCODE 		VARCHAR(20),
	ROAD_ADDRESS 	VARCHAR(500),
	JIBUN_ADDRESS 	VARCHAR(500),
	NAMUJI_ADDRESS 	VARCHAR(500)
);

CREATE TABLE BENEFICIART (
    BENEFICIART_CD			INT AUTO_INCREMENT PRIMARY KEY,
    BENEFICIART_NM			VARCHAR(50),
    BENEFICIART_COMMENT		VARCHAR(2000),
    CONTRIBUTION			INT,
    BENEFICIART_BIRTH		VARCHAR(20),
    BENEFICIART_SEX			VARCHAR(10),
    BENEFICIART_HOBBY		VARCHAR(2000),
    BENEFICIART_FAMILY		VARCHAR(2000),
    BENEFICIART_COUNTRY		VARCHAR(50),
    BENEFICIART_FILE_NAME	VARCHAR(2000)
    
);